import { FC, ReactNode } from 'react';
import '../styles/globals.css';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
};

const RootLayout: FC<Readonly<Props>> = ({ children }) => {
  return (
    <html lang="en">
      <body className="h-dvh w-dvw overflow-hidden dark">{children}</body>
    </html>
  );
};

export default RootLayout;
