import { FC, ReactNode } from 'react';
import '../styles/globals.css';

import type { Metadata } from 'next';

import { StoreProvider } from '@/store';
import { Container, ErrorBoundary, Header } from '@components/layout';

export const metadata: Metadata = {
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
};

const themeScript = `
(function () {
  try {
    var stored = localStorage.getItem('theme');
    var theme = stored ? JSON.parse(stored) : null;
    var isDark = theme === 'dark' || (!theme && matchMedia('(prefers-color-scheme: dark)').matches);
    document.documentElement.classList.toggle('dark', isDark);
  } catch (e) {}
})();
`;

const RootLayout: FC<Readonly<Props>> = ({ children }) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
        <title>Create Next App</title>
      </head>
      <body className="flex h-dvh w-dvw flex-col overflow-hidden" suppressHydrationWarning>
        <StoreProvider>
          <ErrorBoundary>
            <Header />
            <Container className="min-h-0 flex-1">{children}</Container>
          </ErrorBoundary>
        </StoreProvider>
      </body>
    </html>
  );
};

export default RootLayout;
