import { FC, ReactNode } from 'react';
import '../styles/globals.css';

import type { Metadata } from 'next';

import { StoreProvider } from '@/store';
import { Container, ErrorBoundary, Header } from '@components/layout';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
};

const RootLayout: FC<Readonly<Props>> = ({ children }) => {
  return (
    <html lang="en">
      <body className="flex h-dvh w-dvw flex-col overflow-hidden">
        <StoreProvider>
          <ErrorBoundary>
            <Header />
            <Container className="min-h-0 flex-1">{children}</Container>
          </ErrorBoundary>
        </StoreProvider>
      </body>
    </html>
  );
};

export default RootLayout;
