import { type FC, type ReactNode } from 'react';

import type { Metadata } from 'next';
import { notFound } from 'next/navigation';
import { hasLocale, NextIntlClientProvider } from 'next-intl';
import { getMessages, setRequestLocale } from 'next-intl/server';

import { routing, type Locale } from '@/i18n';
import { Container, ErrorBoundary, Header } from '@components/layout';

export const metadata: Metadata = {
  description: 'Generated by create next app',
};

export function generateStaticParams(): { locale: 'en' | 'ru' }[] {
  return routing.locales.map(locale => ({ locale }));
}

type Props = {
  children: ReactNode;
  params: Promise<{ locale: string }>;
};

const themeScript = `
(function () {
  try {
    var stored = localStorage.getItem('theme');
    var theme = stored ? JSON.parse(stored) : null;
    var isDark = theme === 'dark' || (!theme && matchMedia('(prefers-color-scheme: dark)').matches);
    document.documentElement.classList.toggle('dark', isDark);
  } catch (e) {}
})();
`;

const LocaleLayout: FC<Readonly<Props>> = async ({ children, params }) => {
  const { locale } = await params;

  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  setRequestLocale(locale);
  const messages = await getMessages();

  return (
    <html lang={locale} suppressHydrationWarning>
      <head>
        <script dangerouslySetInnerHTML={{ __html: themeScript }} />
        <title>Create Next App</title>
      </head>
      <body className="flex h-dvh w-dvw flex-col overflow-hidden" suppressHydrationWarning>
        <ErrorBoundary>
          <NextIntlClientProvider locale={locale as Locale} messages={messages}>
            <Header />
            <Container className="flex min-h-0 flex-1 flex-col">{children}</Container>
          </NextIntlClientProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
};

export default LocaleLayout;
